### ISSUE TITLE
Some PICT resources are cut off / not decoding properly

### ISSUE THREAD

**Issue by badmotorfinger** [jorio/rsrcdump#5]
I have an example of two graphics which decoded correctly in the mono version of the resource file but was cut short in the colour resource file.

Examples:

Mono
![1001](https://user-images.githubusercontent.com/441719/233902349-b47f4bbf-85f3-40ea-ab17-d39f77412acb.png)

Color
![1001](https://user-images.githubusercontent.com/441719/233902364-a95dd3f8-45c8-47df-b6f6-4c1fc06819ed.png)

Resources attached for reference
[files.zip](https://github.com/jorio/rsrcdump/files/11306672/files.zip)

**Comment by jorio** [comment]
@badmotorfinger, I just pushed a fix for this, please try the latest version.

**Comment by badmotorfinger** [comment]
Perfect! Thank you so much yet again.
